### ISSUE TITLE
concurrency error between 180 and 181: testdata/bert2

### ISSUE THREAD

**Issue by tomspur** [shedskin/shedskin#211]
From #210:

> Test 180 only fails when 181 runs and overwrites it's testdata/bert2 files because 181 doesn't include hello since it's not used by 181.py, but 180 does use it in 180.py. It's purely a concurrency issue

**Comment by srepmub** [comment]
fixed by using a different version of bert.py for each test importing it. looks like there are no other overlapping imports in testdata. don't think it's worth it to do anything more fancy here.
