### ISSUE TITLE
Unbundle/use alternative to murmur hash

### ISSUE THREAD

**Issue by tomspur** [shedskin/shedskin#215]
One possibility would be [boost::hash](http://www.boost.org/doc/libs/1_47_0/doc/html/hash.html) or [std::hash](http://en.cppreference.com/w/cpp/utility/hash).

**Comment by Arkanosis** [comment]
Hi! What's the issue with murmur?

**Comment by tomspur** [comment]
It would be nice to [unbundle](https://fedorahosted.org/fpc/ticket/39) it from shedskin and as there is `std::hash` available it would be nice to use standard c++ functionalities where possible.

**Comment by Arkanosis** [comment]
I see, thanks :)

**Comment by folkertvanheusden** [comment]
See https://github.com/shedskin/shedskin/pull/294
