### ISSUE TITLE
cffi support

### ISSUE THREAD

**Issue by stuaxo** [shedskin/shedskin#216]
CFFI lets you integrate C and Python code.

https://cffi.readthedocs.org/en/latest/

It is the successor to ctypes and enables the user to only know C and python.

simple example

``` python
>>> from cffi import FFI
>>> ffi = FFI()
>>> ffi.cdef("""
...     int printf(const char *format, ...);   // copy-pasted from the man page
... """)
>>> C = ffi.dlopen(None)                     # loads the entire C namespace
>>> arg = ffi.new("char[]", "world")         # equivalent to C code: char arg[] = "world";
>>> C.printf("hi there, %s!\n", arg)         # call printf
hi there, world!
17                                           # this is the return value
>>>
```

**Comment by fahhem** [comment]
I've seen CFFI and like it a lot. How do you envision shedskin would use it?

**Comment by stuaxo** [comment]
If it would enable bindings to existing python based cffi libraries, that would be interesting.

While, for instance cairocffi and pysdl2-cffi bind libraries written in C, it  is nice to be able to use them from shedskin with a python style of programming, the same could be said for pysoundcard and other libraries.

Cffi itself was made by the pypy guys and they seem to have quite a helpful mailing list... 

Not sure whether it would be easiest to get cffi itself working or for shedskin to have its own implementation.

**Comment by stuaxo** [comment]
Shedskin would need to be able to get the types from cffi http://cffi.readthedocs.org/en/latest/using.html and convert them to it's own types during compilation.

From there it should be possible for code in shedskin to call code in cffi libraries.

This would hopefully mean that it could use any python libs that have cffi bindings, but end up with purely native code.

**Comment by fahhem** [comment]
That sounds pretty nice, but I don't see how it would come to be. Can you
give an example of a module with python and cffi bindings that could drop
the cffi intermediary if shedskin did the right stuff?

**Comment by stuaxo** [comment]
Two I've used recently are cairocffi and pysoundcard.   - Potentially there are any modules that switch over to cffi to work with numpy, so possibly numpypy, and many others.


Before adding a mapping between shedskin types and there's probably a bunch of other stuff that doesn't work, I thought I'd see what came up trying to use shedskin with those two modules.




cairocffi seems to do more 'clever' things so I'll cover those at the end and pysoundcard first.

cffi
----

general stuff from cffi:

Uses relative imports, though all from '.' - e.g.
```python
from .api import FFI, CDefError, FFIError
from .ffiplatform import VerificationError, VerificationMissing
```

imports 'types'

Makes sense.  I copied types.py into the cffi directory, but then hit ```*ERROR* cffi/types.py:12: 'type' function is not supported```

Maybe these can be replaced with shedskin equivilents?
```python
$ grep "type(" types.py
NoneType = type(None)
# StringTypes is already outdated.  Instead of writing "type(x) in
FunctionType = type(_f)
LambdaType = type(lambda: None)         # Same as FunctionType
CodeType = type(_f.func_code)
GeneratorType = type(_g())
ClassType = type(_C)
UnboundMethodType = type(_C._m)         # Same as MethodType
InstanceType = type(_x)
MethodType = type(_x._m)
BuiltinFunctionType = type(len)
BuiltinMethodType = type([].append)     # Same as BuiltinFunctionType
ModuleType = type(sys)
    TracebackType = type(tb)
    FrameType = type(tb.tb_frame)
EllipsisType = type(Ellipsis)
DictProxyType = type(TypeType.__dict__)
NotImplementedType = type(NotImplemented)
GetSetDescriptorType = type(FunctionType.func_code)
MemberDescriptorType = type(FunctionType.func_globals)
```


pysoundcard
-----------------

Hit the same type error as above.

cairocffi
----------

Here's a tiny cairocffi example
    https://gist.github.com/stuaxo/453e460797096c37bb41


Cairocffi does quite a lot of 'clever' things that don't make life easy

Relative imports - Like in CFFI these are all seem to be from '.'
    https://github.com/SimonSapin/cairocffi/blob/master/cairocffi/__init__.py#L16


Imports inside try/catch - this is mostly to support python3, I just commented these
     https://github.com/SimonSapin/cairocffi/blob/master/cairocffi/compat.py#L16


Non-global function
```*ERROR* cairocffi/compat.py:43: non-global function 'pixel'```

The code in question:
```
if sys.byteorder == 'little':
    def pixel(argb):
        """Convert a 4-byte ARGB string to native-endian."""
        return argb[::-1]
else:
    def pixel(argb):
        """Convert a 4-byte ARGB string to native-endian."""
        return argb
```

Not sure if shedskin can know that this is actually a global function, and that sys.byteorder is constant?


Uses ```ctypes.util.find_library(lib_name)``` and ```ctypes.dlopen```

After fixing some more stuff with relative imports I hit the error about the 'type' function.

**Comment by stuaxo** [comment]
I guess... some of these unsupported things are stuff that would happen at the time of type-inference, when it's just normal python - so maybe not as problematic as it might seem?

**Comment by srepmub** [comment]
closing ~10-year old issues. please reopen if interested/willing to implement it :)
