### ISSUE TITLE
Support relative imports

### ISSUE THREAD

**Issue by stuaxo** [shedskin/shedskin#218]
Python codebases use relative imports these days, it'd be nice if shedskin supported them.

https://docs.python.org/2.5/whatsnew/pep-328.html

**Comment by retsyo** [comment]
any tutorial to lead other people try to add more feature in ss? I try to ss my python 2.7 app, however met some questions, among of which is the same "relative imports"

**Comment by srepmub** [comment]
these should more or less work now.  still need to add some tests before closing the issue.

**Comment by srepmub** [comment]
tests added
