### ISSUE TITLE
Unknown exception type - would be nice if it specified the exception

### ISSUE THREAD

**Issue by stuaxo** [shedskin/shedskin#219]
I was playing with the code from CFFI and got this error

```
*ERROR* api.py:25: unknown or unsupported exception type
```

The bit of code in question looks like this:

```
class CDefError(Exception):
    def __str__(self):
        try:
            line = 'line %d: ' % (self.args[1].coord.line,)
        except (AttributeError, TypeError, IndexError):
            line = ''
        return '%s%s' % (line, self.args[0])
```

It would be great if the error message specified which exception is the unsupported one.

**Comment by stuaxo** [comment]
Update:  It seems to be AttributeError in this case.

**Comment by srepmub** [comment]
ahem, sorry for the 'late' reply..!

I think we based the builtin exceptions on the following list, though probably for 2.5 or 2.6:

https://docs.python.org/2/library/exceptions.html

though AttributeError should have existed by then, perhaps I missed it.

I will update the exceptions for the 2.7 list shortly. note: let's check python 3 or so while at it..

agreed the error message should also be better! I will patch this a bit for 0.9.5.

**Comment by srepmub** [comment]
hmm okay so perhaps I left it out because it's not really supported :P your point still stands then, it should at least mention what is not known/supported.

**Comment by stuaxo** [comment]
To make things quick to reference, here's the list for python 3 (aspirational right now I assume!)

https://docs.python.org/3/library/exceptions.html

**Comment by srepmub** [comment]
thanks! yes, planning to go over this list in the coming days as one of the still open points to reach basic python3 compatibilty..

**Comment by srepmub** [comment]
updated the hierarchy structure for python3, and it should now print which exception type is unknown/unsupported (at least for bulitins :P). thanks!
