### ISSUE TITLE
Wrong results (0 instead of correct floating point values) for a puzzle

### ISSUE THREAD

**Issue by ttsiodras** [shedskin/shedskin#223]
Hi - after watching a Numberphile video about coin tosses, I wrote this...

    #!/usr/bin/env python3
    from random import choice;
    
    experiments = 0
    experiment_lengths = 0
    
    while(True):
        res = ''
        while not res.endswith('HHH'):
            res += choice(['H', 'T'])
        experiment_lengths += len(res)
        experiments += 1
        if experiments % 1000 == 0:
            print("Running average (%d tosses): %f" % (
                experiments, float(experiment_lengths)/experiments))

...which confirmed (under CPython 3) that the average number of tosses you need to get three heads in a row tends towards 14:

    $ python3 coin_tosses.py 
    Running average (1000 tosses): 14.650000
    Running average (2000 tosses): 14.527500
    ...
    Running average (148000 tosses): 14.021088
    Running average (149000 tosses): 14.021034
    Running average (150000 tosses): 14.026173
    ....

But when I compiled my Python code with Shedskin, I saw this instead:

    $ make
    ...
    $ ./coin_tosses | head
    Running average (1000 tosses): 0.000000
    Running average (2000 tosses): 0.000000
    Running average (3000 tosses): 0.000000
    Running average (4000 tosses): 0.000000
    Running average (5000 tosses): 0.000000
    Running average (6000 tosses): 0.000000
    Running average (7000 tosses): 0.000000
    Running average (8000 tosses): 0.000000
    Running average (9000 tosses): 0.000000
    Running average (10000 tosses): 0.000000
    
Any idea why?

**Comment by ttsiodras** [comment]
Wow - that was fast. Thanks!

**Comment by Arkanosis** [comment]
There was a bug in str.endswith; thanks for reporting :)
