### ISSUE TITLE
dedent missing (module.cpp.tpl)

### ISSUE THREAD

**Issue by ttsiodras** [shedskin/shedskin#224]
When I used ShedSkin to process the python script from this repo:

    https://github.com/ttsiodras/PrimeSpirals

...I get this error:

    shedskin primeSpirals.py 
    *** SHED SKIN Python-to-C++ Compiler 0.9.4 *** - 
    ...
    [generating c++ code..]
        File "/home/ttsiod/.local/lib/python2.7/site-packages/shedskin/templates/cpp/module.cpp.tpl", line 2, in top-level template code
        {% block docs %}
      File "/home/ttsiod/.local/lib/python2.7/site-packages/shedskin/templates/cpp/module.cpp.tpl", line 7, in block "docs"
        {% set lines = dedent('\n'.join(doc[1:])).splitlines() %}
    jinja2.exceptions.UndefinedError: 'dedent' is undefined

I am guessing it has to do with the docstring in the script... If I remove the `lines`-related section of the jinja2 module.cpp.tpl template, then everything works.

**Comment by Arkanosis** [comment]
There was indeed a missing template rendering parameter; thanks for reporting :)
