### ISSUE TITLE
How to get it working on Ubuntu

### ISSUE THREAD

**Issue by jplevyak2** [shedskin/shedskin#225]
git clone https://github.com/shedskin/shedskin.git
pip install blessings jinja2 progressbar
cd shedskin

Apply the patch:

diff --git a/shedskin/infer.py b/shedskin/infer.py
index a1b1ecd..d312650 100644
--- a/shedskin/infer.py
+++ b/shedskin/infer.py
@@ -1069,6 +1069,7 @@ def update_progressbar(gx, perc):
             maxval=1,
             term_width=33
         )
+        gx.progressbar.start();

     with gx.terminal.location(x=0):
         gx.progressbar.update(perc)

sudo python setup.py install
cd ..
sudo cp -r shedskin/templates /usr/local/lib/python2.7/dist-packages/shedskin

**Comment by Arkanosis** [comment]
Hi @jplevyak2 and thanks for the patch!

It should work without modification on Ubuntu, but please not that you have to install the `progressbar2` package instead of the legacy `progressbar` progressbar. This can be misleading as both packages provide the `progressbar` module, but with different properties / API.

See the `requirements.txt` file at the top of shedskin's directory of a (hopefully) complete list of its dependencies.

Is it working for you if you install `progressbar2` instead?

Thanks again!

**Comment by jplevyak2** [comment]
Yes, that works.  I still need to do 

sudo cp -r shedskin/templates /usr/local/lib/python2.7/dist-packages/shedskin

for some reason as it doesn't seem to install the template directory.

**Comment by Arkanosis** [comment]
Interesting… it looks like recurrence of #213. @fahhem does this remind you something?

**Comment by Arkanosis** [comment]
It works for me on Kubuntu 16.04. @jplevyak2, could you please tell me which version of Ubuntu you're using?

Also, I guess the way it is implemented in `build.py` is not very robust to unexpected working directories. Are you actually running `setup.py install` from shedskin's directory?

    templates = []
    for root, _, files in os.walk(os.path.join('shedskin', 'templates')):
        templates.extend(os.path.join(root, f) for f in files)
    # <snip>
    package_data={
        'shedskin': [
            'lib/*.cpp', 'lib/*.hpp', 'lib/builtin/*.cpp', 'lib/builtin/*.hpp',
            'lib/*.py', 'lib/os/*.cpp', 'lib/os/*.hpp', 'lib/os/*.py',
            'FLAGS*', 'illegal'] + templates},

I wonder what would be the drawback of just putting `templates/cpp/*.cpp.tpl` in `package_data` without bothering with `os.walk`? At first sight it looks like it'd be both more straightforward and more robust.

**Comment by Arkanosis** [comment]
@jplevyak2: could you please try again with the latest version from git? Thanks!

**Comment by jplevyak2** [comment]
Works great.  Thanx!

**Comment by Arkanosis** [comment]
Awesome! Thanks for reporting :)
