### ISSUE TITLE
Is it possible to support dynamic type?

### ISSUE THREAD

**Issue by roundsheep** [shedskin/shedskin#226]
From my opinion, dynamic type is very important for the dynamic languages, thanks a lot.

**Comment by Arkanosis** [comment]
Hi @roundsheep and thanks for the comment.

Why do you mean exactly by « dynamic type »? This a very wide subject. Any concrete use case that we could try to address?

Thanks again!

**Comment by roundsheep** [comment]
From the document of this project, there is some restrict in it, for example, a=[1,'abc']  a=[1,2] will get an error, this is not really Python, I try to write a JavaScript to C++ translator recently, I also want to get a Python to C++ translator, I think translate Python to JavaScript is easy.

**Comment by fahhem** [comment]
If you want a=[1, 'a'] and then a=[1,2] to work, then consider Cython. shedskin
is meant to essentially allow you to write C++ with Python syntax. If you can't
do something in C++, then you can't do it in shedskin'able Python





On Tue, Aug 30, 2016 1:32 AM, roundsheep notifications@github.com wrote:
From the document of this project, there is some restrict in it, for example,
a=[1,'abc'] a=[1,2] will get an error, this is not really Python, I try to write
a JavaScript to C++ translator recently, I also want to get a Python to C++
translator, I think translate Python to JavaScript is easy.

**Comment by pfalcon** [comment]
> If you want a=[1, 'a'] and then a=[1,2] to work, then consider Cython.

Or perhaps https://github.com/Nuitka/Nuitka . Buy yep, it's pretty sad that shedskin doesn't support List[Any].

**Comment by srepmub** [comment]
yeah, this is not going to happen. the whole idea behind shedskin is to restrict things, so we can actually do type inference (otherwise intractable) and compile python code down to machine code for ultimate performance.. :P
