### ISSUE TITLE
String Formatting Performance

### ISSUE THREAD

**Issue by CrazyPython** [shedskin/shedskin#229]
the important modfill function in lib/builtin.cpp can probably become a lot faster by building the result in one go, instead of using many intermediate allocations. we probably want to implement our own asprintf function. something similar holds for many repr methods..

_migrated from [the easytasks list](https://code.google.com/archive/p/shedskin/wikis/easytasks.wiki)_

**Comment by srepmub** [comment]
string formatting is usually not the bottleneck, so not that important. close for now.
