### ISSUE TITLE
Speed up itertools.product

### ISSUE THREAD

**Issue by CrazyPython** [shedskin/shedskin#230]
the performance of this common function can be improved in at least two ways, as was done for the zip(a,b) implementation: preallocate tuples if their number is known, and use FOR_IN type iteration. (first part was done for 0.9.1)

_migrated from [the easytasks list](https://code.google.com/archive/p/shedskin/wikis/easytasks.wiki)_

**Comment by srepmub** [comment]
itertools.product does not seem general enough to warrant a FOR_IN_PRODUCT macro at this point I think. let's have another look if there is an actual example that would benefit from this.
