### ISSUE TITLE
Investigate cygwin vs. mingw

### ISSUE THREAD

**Issue by CrazyPython** [shedskin/shedskin#231]
Could this work, and would it lessen the pain of supporting windows?

_migrated from [the easytasks list](https://code.google.com/archive/p/shedskin/wikis/easytasks.wiki)_

**Comment by srepmub** [comment]
egh, I think we can close this, and wait for any PR on this front.. which I doubt there will ever be :package:

with WSL, there is even less of a reason to bother with windows support :P (though of course this isn't entirely the same)
