### ISSUE TITLE
Speed up strings

### ISSUE THREAD

**Issue by CrazyPython** [shedskin/shedskin#233]
Profile and optimize commonly used string methods. In the long term, we want to replace the STL strings with a cpython-based implementation, but that's a lot of work.

_migrated from [the easytasks list](https://code.google.com/archive/p/shedskin/wikis/easytasks.wiki)_

**Comment by srepmub** [comment]
on second thought, not so sure anymore about the latter, and I think we can do this as issues turn up from profiling test programs.
