### ISSUE TITLE
Parameterize double type

### ISSUE THREAD

**Issue by CrazyPython** [shedskin/shedskin#234]
For ints, we use a special `ss_int` type that can be changed from a single line (shedskin -l does this). For floats, it would be nice to do something similar, so we can lower/increase precision at will.

_migrated from [the easytasks list](https://code.google.com/archive/p/shedskin/wikis/easytasks.wiki)_

**Comment by srepmub** [comment]
good point, agreed that would be nice/useful.

**Comment by srepmub** [comment]
(think I just agreed with myself)

**Comment by srepmub** [comment]
just started pushing commits for this. the following benchmark becomes about 30% faster on my system:

for x in range(100):
    a = [1.1 for a in range(1000000)]
    s = sum(a)
print(s)

**Comment by srepmub** [comment]
running into issues with the use of va_arg, which has problems with floats (non-double). there is probably a nice way to replace the crappy va_arg stuff in modern C++.. (variadic templates?)

**Comment by srepmub** [comment]
tagging with 0.9.9 as 0.9.8 removes the va_arg stuff.

**Comment by srepmub** [comment]
added --float32
