### ISSUE TITLE
Arbitrary size arithmetic

### ISSUE THREAD

**Issue by CrazyPython** [shedskin/shedskin#237]
Might be quite a bit of work, but long term it would be nice to support arbitrary-size integer arithmetic through something like libgmp. note the `typedef ss_int` statement in the top of `lib/builtin.hpp`.

_migrated from [the easytasks list](https://code.google.com/archive/p/shedskin/wikis/easytasks.wiki)_

**Comment by CrazyPython** [comment]
My personal comment (not migrated): this may be bad for performance. Should only be enabled with a flag.

**Comment by Arkanosis** [comment]
> this may be bad for performance. Should only be enabled with a flag.

I heartily agree with this :)

**Comment by srepmub** [comment]
of course, yes, the nice thing about shedskin is that you get to choose your int type. you can even choose different types for different (extension) modules.

but let's be honest, probably not an easy task to perform the required surgery.

**Comment by srepmub** [comment]
for 0.9.9 we should have --float32/float64/int32/int64/int128 options to override default double/int types.

don't think having this issue open will make anyone ever start working on it (I won't), so closing.
