### ISSUE TITLE
struct and ieee754

### ISSUE THREAD

**Issue by CrazyPython** [shedskin/shedskin#239]
(un)packing floats on hardware that doesn't natively use ieee754 format currently doesn't work.

_migrated from [the easytasks list](https://code.google.com/archive/p/shedskin/wikis/easytasks.wiki)_

**Comment by srepmub** [comment]
which reasonably available hardware could we test this with..?

**Comment by srepmub** [comment]
I think we need a specific use case for this, so we can also verify a fix.

https://stackoverflow.com/questions/2234468/do-any-real-world-cpus-not-use-ieee-754
