### ISSUE TITLE
execinfo.h: No such file or directory - error on Mac OS X

### ISSUE THREAD

**Issue by programmingkidx** [shedskin/shedskin#240]
When I try compiling a simple python file, I see this error message a lot:

error: execinfo.h: No such file or directory

http://stackoverflow.com/questions/28680323/the-execinfo-h-header-file-does-not-exist
According to this page this file is Linux only. I am using Mac OS 10.4.

**Comment by Arkanosis** [comment]
Thanks for the report.

I'm not sure anyone is using MacOS there, would you mind trying the following to see if it's enough to fix the issue?

1. In `shedskin/lib/builtin.hpp`, replace

    #include <execinfo.h>

… with

    #ifndef __APPLE__
    # include <execinfo.h>
    #endif

2. In `shedskin/lib/builtin/exception.hpp`, replace

    #ifndef WIN32

… with

    #if !defined(WIN32) && !defined(__APPLE__)

Thanks!

**Comment by programmingkidx** [comment]
Thank you. Your suggestions worked. I was able to make a binary that didn't depend on Python. Your code should be committed to this repo.

**Comment by Arkanosis** [comment]
Good to hear! Thank you again for the report and the time you took to test the fix :)
