### ISSUE TITLE
Undocumented requirements?

### ISSUE THREAD

**Issue by dare0021** [shedskin/shedskin#244]
While trying to get Shedskin set up, I got stuck at the "make" portion of the install process with the following problems:

> test.cpp:1:0:
> /usr/local/lib/python2.7/dist-packages/shedskin/lib/builtin.hpp:10:29: fatal error: gc/gc_allocator.h: No such file or directory
> compilation terminated.
> In file included from /usr/local/lib/python2.7/dist-packages/shedskin/lib/re.hpp:9:0,
>                  from /usr/local/lib/python2.7/dist-packages/shedskin/lib/re.cpp:3:
> /usr/local/lib/python2.7/dist-packages/shedskin/lib/builtin.hpp:10:29: fatal error: gc/gc_allocator.h: No such file or directory
> compilation terminated.
> In file included from /usr/local/lib/python2.7/dist-packages/shedskin/lib/builtin.cpp:3:0:
> /usr/local/lib/python2.7/dist-packages/shedskin/lib/builtin.hpp:10:29: fatal error: gc/gc_allocator.h: No such file or directory
> compilation terminated.
> Makefile:17: recipe for target 'test' failed
> make: *** [test] Error 1

After some googling, I solved the problem by installing 2 libraries:
libgc-dev
libpcre3-dev
and was able to complete the install process, with the hello world program running correctly.

I suspect the two are fairly common libraries that went undocumented due to them being so common?

**Comment by Arkanosis** [comment]
Thanks again, @dare0021 !

This is actually documented in [the full documentation](https://shedskin.readthedocs.io/en/latest/documentation.html#unix).

Looks like having a “short” documentation in the `README.md` is in fact worse than nothing, as nobody wants to take the long path when there seems to be a shorter one.

I suggest we remove the “Installation” paragraph from the `README.md` and link to the right page in the documentation instead (where we should add `pip install -r requirements.txt` as well — I haven't found it anywhere).

I may do it tonight, but if you want to take credit for the change (you deserve it), feel free to submit a pull request :)

**Comment by Arkanosis** [comment]
> > and link to the right page in the documentation instead
> 
> But why instead, why not in addition to the existing short instructions?

Well, I hate doing twice the same thing, and taking the risk of having both diverge because someone takes care of updating one but forgets the other. Having everything in one place is the only approach which is proven to avoid that.

Just my opinion, though.

**Comment by srepmub** [comment]
I made some changes to the README. to hopefully lead to less unexpected results for first-time users.

feel free to re-open the issue if you still feel like something should be changed.
