### ISSUE TITLE
Support for argparse module

### ISSUE THREAD

**Issue by kb-1000** [shedskin/shedskin#254]
Please add support for the argparse module, or at least supply a replacement that behaves similar (API compatibility is not important if you use a replacement).

**Comment by srepmub** [comment]
thanks for the suggestion.

**Comment by srepmub** [comment]
this module may be difficult or impossible though to support (fully), because of dynamic typing.

**Comment by kimstik** [comment]
> this module may be difficult or impossible though to support (fully), because of dynamic typing.

Argparse is a module that is sorely lacking. Even partial support for its functionality will be valuable.

**Comment by srepmub** [comment]
note that you can still use it via an extension module.

but not much point in keeping issues for module requests open, so closing.
