### ISSUE TITLE
can't use under Windows 7

### ISSUE THREAD

**Issue by retsyo** [shedskin/shedskin#260]
The reason is that `blessings` module needs to `import curses` which is not available on windows

so any  hints?

**Comment by retsyo** [comment]
https://github.com/jquast/blessed can be used to replace blessings on windows

**Comment by folkertvanheusden** [comment]
Did not test it but what about https://pypi.org/project/windows-curses/ ?

**Comment by srepmub** [comment]
just to mention: if WSL is an option, shedskin should work just fine under it.

**Comment by retsyo** [comment]
https://github.com/shedskin/shedskin/pull/265 can solve the problem

btw, WSL is a heavy toy for programmer, I don't have free harddisk space for it.
