### ISSUE TITLE
subprocess module problem

### ISSUE THREAD

**Issue by SlaSerX** [shedskin/shedskin#268]
Hello how can fix thix 

root@lab:~# shedskin a.py 
*** SHED SKIN Python-to-C++ Compiler 0.9.4 *** - 
Copyright 2005-2019 Mark Dufour and contributors; License GNU GPL version 3 (See LICENSE)

*ERROR* a.py:3: cannot locate module: subprocess

**Comment by dstromberg** [comment]
I do not think shedskin supports the subprocess module:
https://shedskin.readthedocs.io/en/latest/documentation.html
(Look for the "LIbrary Limitations" section).

Also, shedskin is Python 2.x-only, and unlikely to make the jump to 3.x.

HTH.

**Comment by pfalcon** [comment]
> and unlikely to make the jump to 3.x.

Why suddenly? There're enough pullrequests trying to do that, someone confirmed should just re-do them in clean manner (and likely fork and maintain the 3.x version, yeah).

**Comment by dstromberg** [comment]
On Thu, Feb 11, 2021 at 2:40 PM Paul Sokolovsky <notifications@github.com>
wrote:

> and unlikely to make the jump to 3.x.
>
> Why suddenly? There're enough pullrequests trying to do that, someone
> confirmed should just re-do them in clean manner (and likely fork and
> maintain the 3.x version, yeah).
>
We could fork it and work on such a port, but I believe the original author
is uninterested.  And he believes that it would be difficult for anyone but
him to do it.

-- 
Dan Stromberg

**Comment by pfalcon** [comment]
> We could fork it and work on such a port, but I believe the original author is uninterested.

It was education-years project, and he maintained it for quite a few years afterwards (most people drop their student projects as soon as they graduate). But sure, people move on.

> And he believes that it would be difficult for anyone but him to do it.

Then it would a good challenge to go for, right? ;-)

All in all, I personally still consider hacking on shedskin in my queue, but I'm not in hurry at all, as there're many Python compiler projects/ideas around. (And I have strong affinity for minimalist projects, and shedskin isn't exactly such.)

**Comment by SlaSerX** [comment]
> On Thu, Feb 11, 2021 at 2:40 PM Paul Sokolovsky ***@***.***> wrote: and unlikely to make the jump to 3.x. Why suddenly? There're enough pullrequests trying to do that, someone confirmed should just re-do them in clean manner (and likely fork and maintain the 3.x version, yeah).
> We could fork it and work on such a port, but I believe the original author is uninterested. And he believes that it would be difficult for anyone but him to do it.
> […](#)
> -- Dan Stromberg

hello where i can find your port version

**Comment by alextretyak** [comment]
@SlaSerX
Can you elaborate on which functions of subprocess module do you need?
And why you want Shed Skin to support this? Have you tried other tools for accelerating Python code (such as PyPy and Cython)?
The thing is I am also developing a Python-to-C++ transpiler, and now I'm looking for tasks/problems which can be solved with it, as the development of this transpiler is task-driven (as I explained [here](https://forum.11l-lang.org/threads/supported-modules.10/#post-27)).
