### ISSUE TITLE
This project does not work with modern Python 3, please define what Python versions are supported

### ISSUE THREAD

**Issue by dmikushin** [shedskin/shedskin#271]
I've tried the fixes offered in PRs, but shedskin is still incompatible with the modern versions of Python, such as 3.9. The Python internal AST module keeps changing, so I get

```
ImportError: cannot import name 'Print' from 'ast' (/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py)
```

To avoid mis-expectations, please consider defining what specific versions of Python are supported.

**Comment by AstroFloof** [comment]
> Shed Skin is an experimental compiler, that can translate pure, but implicitly statically typed Python (2.4-2.6) programs into optimized C++. It can generate stand-alone programs or extension modules that can be imported and used in larger Python programs.

**Comment by dmikushin** [comment]
That's a pity!
