### ISSUE TITLE
11l transpiler is faster for specific test case

### ISSUE THREAD

**Issue by srepmub** [shedskin/shedskin#273]
see the second example here:

https://11l-lang.org/transpiler/

I investigated why the 11l generated code is so much faster, and the reason seems to be that shedskin is using 4 bytes to store a boolean (shedskin/lib/builtin.hpp, class __ss_bool), which I guess in this case causes worse caching behaviour.

I quickly patched things to check that indeed this is the difference. I will provide a tested patch shortly.

**Comment by srepmub** [comment]
btw so this seems to be a transpiler relying on C++ auto keyword. not sure how well that scales for larger programs :P

**Comment by vonj** [comment]
Why?

**Comment by srepmub** [comment]
I guess because types are often not obvious from the immediate context. you might try replacing all type declarations in a large C++ program with 'auto' and see what happens, or try one of the larger shedskin example programs with ll1..

**Comment by srepmub** [comment]
bool case done. other case not that interesting.
