### ISSUE TITLE
python3: support unicode

### ISSUE THREAD

**Issue by srepmub** [shedskin/shedskin#275]
-add bytes/unicode distinction in type inference
-add unicode type to cpp backend
-"fix" standard module implementations

**Comment by srepmub** [comment]
added a 'unicode' class to shedskin/lib/builtin.py, that is used for u'strings'. still lots of work left, both on the python and cpp side.

**Comment by srepmub** [comment]
currently thinking about 'faking' unicode support for the first python3-only release, if possible, by reusing the python2 str implementation (and error out if an unsupported character is encountered?). 

what probably needs to happen for full unicode support in any case, is to parameterize the 'str' class, so we have eg typedef bytes  _str<char> and typedef str _str<char32_t>. and make lib/builtin/str.cpp consider the different char types.

for the 're' module it looks like we can just use libpcre32, and parameterize things in the same way.

but it's quite a bit of effort, where most code that would be useful to compile doesn't really need unicode support (and we sure don't want any slowdowns because of it).

another thing we might want is to add an option to specify unicode 'precision' like we do for ints (and would like to do for floats) (that way we can also avoid any slowdown).

**Comment by humhue** [comment]
So, `str` is utf8, `bytes` is just bytes, right? I started extending Shed Skin by writing my own C++ functions, I needed to convert from utf16 to utf8 and from utf8 to utf16, it was quite easy to do so in a portable way by using utfcpp. I would just ignore `re` for now but it would be handy to be able to specify the desired unicode precision for `re`.
Do we still want to parameterize `str`?

**Comment by srepmub** [comment]
sorry for the late reply, had a busy week.

str is currently more of a bytes type than text. in fact the two are almost identical. the reason for having two separate implementations is that they are typed differently, for example indexing a bytes object returns an integer instead of a 1-length str.

the used encoding is also not guaranteed to be utf-8.

ideally the str and bytes type share most of their implementation, while also being able to handle arbitrary unicode characters. that is quite some work though.

**Comment by srepmub** [comment]
let me create a new issue, as the comments above are outdated.
