### ISSUE TITLE
python3: port examples to python3

### ISSUE THREAD

**Issue by srepmub** [shedskin/shedskin#277]
fortunately there are only 75 of them! :S

of course this allows for additional testing of python3 support. if the builtins and example programs work, we are basically there.

**Comment by shakfu** [comment]
By the way, it's great to see this project revived for python3... :smile:

I have made some partial progress on this (see my fork: https://github.com/shakfu/shedskin) 

The `examples3` folder contains converted and tested python3 versions, `examples_2t3` are in process but still buggy and `examples` are the old python2 examples.

**Comment by srepmub** [comment]
thanks a lot for the help! :-) I started merging your changes for LZ2 into examples/, and then realized you are probably right to start a new examples3/ dir. so I will copy over your example3 dir shortly. thanks again!

**Comment by srepmub** [comment]
okay, I copied over your examples3/ directory, and added a few missing testdata files. looking good!

I don't think we need to merge examples_2t3. nicest would probably be to send in a pull request whenever you have finished porting one or more examples.

**Comment by shakfu** [comment]
Thanks. @srepmub 

Definitely agree it doesn't make sense to merge `examples_2t3` It was just a working directory so I could keep track of what remained.

**Comment by srepmub** [comment]
I'm currently looking into gs_main.py (Gh0stenstein).. (apparently the python gtk bindings have also drastically changed over time.. :P). let me know if anyone else is looking at this, happy to step back :P

**Comment by shakfu** [comment]
Hi @srepmub 

I've generally avoided the examples which had dependencies, preferring to work first on the pure python ones first. But even these can be a pain to convert:  got stuck on [examples2to3/linalg.py](https://github.com/shakfu/shedskin/blob/master/examples2to3/linalg.py)  yesterday which gives slightly different results even though the fix is minor.

**Comment by srepmub** [comment]
Gh0stenstein (gs_main.py) ported to examples3/. I will look at circle_main.py next, which should be a bit less painful I hope.. :P

**Comment by srepmub** [comment]
circle was easy, as pygame hasn't changed apparently (great). will look at pylot_main next. a bit scared of c64_main.py.. that will probably be the last one ported :P

**Comment by shakfu** [comment]
I have made a few more conversions:

```text
examples3/mastermind2.py
examples3/mastermind_main.py
examples3/neural1.py
examples3/sudoku1.py
examples3/sudoku2.py
examples3/sudoku4.py
examples3/timsort.py
```

These are still in my fork: https://github.com/shakfu/shedskin

Probably best to grab them manually now, as my repo is still retaining the intermediate `examples2to3` directory to keep track of what remains.

It's funny how much code of the python2 relies on integer division. A lot of the fixes are changing `/` to `//`

**Comment by srepmub** [comment]
great, thanks! =) merged them, except for mastermind_main.py (did you forget to commit the mm/ dir?)

**Comment by shakfu** [comment]
@srepmub 
> did you forget to commit the mm/ dir

Yes, my bad.. I'll fix that

**Comment by shakfu** [comment]
A few more additions just now. 

Incidentally, I'm stuck on a few 'pairs', I think I have fixed the main files (`pylife.py`, `fysphun.py`, and `mandelbrot2.py`, but the `_main.py` parts are giving me some concern. If you have a chance can you also test them on your side: these are all still in `examples2to3.py`.

```
pylife.py
pylife_main.py # requires curses

fysphun.py
fysphun_main.py # requires pygame

mandelbrot2.py
mandelbrot2_main.py # requires _tkinter
```

**Comment by shakfu** [comment]
Hi @srepmub 

You are right about minilight, the output is different. There must be a mistake in the conversion. Same for bh. I'll revisit both again.

Incidentally, linalg.py should give the same output as the py2 version last time I checked, but check it again of course.

**Comment by shakfu** [comment]
bh is fixed: tricky conversion of `__idiv__` to `__itruediv__`

**Comment by shakfu** [comment]
I'm stuck on `minilight`. I'll park it for now and get some fresh eyes.

**Comment by srepmub** [comment]
fixed fysphun - egh, there were mixed tabs & spaces in the original, causing 'basiclimits()' not to be called, causing everything to fall through the bottom of the pygame screen.

**Comment by srepmub** [comment]
mandelbrot2_main seems to work fine..? :P merged.

for pylife, it looks like there is no floating point division at all, so changing all divisions to // seems to work? merged :)

for minilight, not sure what your approach is, but perhaps it could help to just print for each division what the types are of the arguments? if they are both int, use //, otherwise leave as /. or there may be some other problem of course.. :P

**Comment by srepmub** [comment]
note that I just created a 'python3' branch, where I fixed compilation of examples3/mandelbrot.py (after I changed mandelbrot.py so it relies on python3 division :P). my idea is to just go over all examples, from small to large, and fix whatever is needed in the python3 branch.

**Comment by srepmub** [comment]
ported mwmatching, sokoban, quameon.

**Comment by shakfu** [comment]
I've lost track of what's left. Will have a some time over the weekend to revisit the pesky minilight again.

**Comment by srepmub** [comment]
in the 'python3' branch, the 10 or so smallest examples actually compile already.. progressing faster than I expected ^^ will add functools.reduce next, as a few examples use this.

**Comment by shakfu** [comment]
Great stuff!

**Comment by srepmub** [comment]
ported TonyJpegDecoder. will try to port one remaining example per day.

**Comment by srepmub** [comment]
this is done. they also almost all compile already. so this is looking pretty good.
