### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by folkertvanheusden** [shedskin/shedskin#280]
https://github.com/shedskin/shedskin/blob/4ee1fe0727c300ec2691624175422ccb12c38ac0/shedskin/lib/array.cpp#L75

What about something like:

    case 'b': for(auto & item : *l) *reinterpret_cast<signed char>(&this->units[pos]) = item; pos += itemsize; break;

(not tested but to give an idea).

**Comment by srepmub** [comment]
thanks! seems we have some tests for 'array' in especially 196.py. 

would you be open to making a PR out of this and checking that it's covered by the tests..? P

**Comment by folkertvanheusden** [comment]
I'll close this issue as it won't compile this way (your list-class needs iterators added (begin() and end()) and we need more casting).
