### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by folkertvanheusden** [shedskin/shedskin#281]
https://github.com/shedskin/shedskin/blob/4ee1fe0727c300ec2691624175422ccb12c38ac0/shedskin/lib/datetime.cpp#L286

This is problematic: you're retrieving the current time in two steps (time() and gettimeofday). For example the gettimeofday may return the usec of the _next_ second. Also gettimeofday is obsolete.

Try (not tested) something like:

```
datetime *datetime::today() {
    timespec ts { 0, 0 };

    if (clock_gettime(CLOCK_REALTIME, &ts) == -1) throw new error(make_errstring("clock_gettime"));
    tm *t = localtime( &ts.tv_sec );

    return new datetime(t->tm_year+1900,t->tm_mon+1,t->tm_mday,t->tm_hour,t->tm_min,t->tm_sec,ts.tv_nsec
/ 1000);
}
```

**Comment by srepmub** [comment]
thanks! change already merged via PR. about testing, let me add a test for this in 206.py.. :)
