### ISSUE TITLE
small object performance (esp. tuples)

### ISSUE THREAD

**Issue by srepmub** [shedskin/shedskin#289]
small object allocations are terrible for performance. shedskin currently naively allocates these on the heap. several things can be done to mitigate this:

-pass them by value if possible (tried this in the past, complicated the code quite a bit)
-escape analysis (see resp. issue)
-tell GC to not track contents if no pointers (which I think is already the case)
-use a faster allocator such as tcmalloc (not sure if I tried this before, or if it works with the boehm gc)

the latter two may be quick wins. currently looking into speeding up sunfish, which uses lots of intermediate tuples. some longer than two, like (a,b,c), so that is now rewritten as (a,(b,c)) which generates even more tuples..

**Comment by srepmub** [comment]
for this little program, a bit of a worst case scenario:

for i in range(50000000):
    t = (1, ('hoi', 18))

cpython2 takes about 2.67 seconds (best of three).

whereas the 'skinned' version takes about 9.89 seconds (I guess cpython is well optimized for small object allocation, and malloc isn't..)

since boehm gc seems to just hook into malloc and such, we can actually just LD_PRELOAD another allocator, potentially much faster with small objects such as mimalloc, jemalloc or tcmalloc.

for me jemalloc turns out fastest for this test case:

LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 ./tupletest

this makes the run-time drop to 5.89 seconds..

unfortunately for the new sunfish test case, this doesn't seem to help.

I haven't tested this with any other code.

**Comment by vonj** [comment]
In these situations, I think it’s always helpful to see what the speed would be without garbage collection. (Just let it leak.) It shows a lower bound.

**Comment by vonj** [comment]
And I will also add, for some workloads it’s a perfectly fine strategy to never garbage collect.

**Comment by srepmub** [comment]
yeah, I think was also an issue about disabling GC with a shedskin command-line flags.

**Comment by srepmub** [comment]
in python this construct is often used (and in the new sunfish example all over the place - it's great for readability :)):

if x in (a, b): ..

currently, shedskin heap-allocates a tuple, but in many cases we can automatically optimize this, instead of requiring a manual change (if x == a or x ==b).

**Comment by srepmub** [comment]
note that this optimization was implemented in the meantime.

**Comment by srepmub** [comment]
closing for more general issue.
