### ISSUE TITLE
Windows usage: request for comment

### ISSUE THREAD

**Issue by carlkl** [shedskin/shedskin#348]
_I propose an update to the windows related part of the documentation:_

Use **Msys2**, the Software Distribution and Building Platform for Windows: https://www.msys2.org/

Learn about the environments/subsystems provided by **Msys2**:
https://www.msys2.org/docs/environments/

For Windows 64-bit development you want to use the **UCRT64** environment.
For Windows 32-bit development you want to use the **MINGW32** environment.

Start the environment of your choice with a terminal shell:  `UCRT64.exe` or `MINGW32.exe`

Use the `pacboy` command instead of `pacman` to avoid the need to use fully qualified 
package names: `<name>:p means MINGW_PACKAGE_PREFIX-only`.
For information about `pacboy` read https://www.msys2.org/docs/package-naming/

Install these packages one after the other from your shell:

``` shell
$ pacman -S pacboy
$ pacboy -S toolchain:p
$ pacboy -S clang:p
$ pacboy -S gc:p
$ pacboy -S pcre:p
$ pacboy -S python:p
$ pacboy -S python-six:p
$ pacboy -S python-jinja:p
$ pacboy -S python-pip:p
```
Install these python packages from **PyPI** within staying in your shell as there is 
no **Msys2** support at the time of writing for these packages:

``` shell
$ python -m pip install progressbar2
$ python -m pip install blessings
$ python -m pip install python-utils
```
Now you should be able to install an test shedskin.

**Comment by srepmub** [comment]
looks good to me, thank you! =) would you be willing to create a PR for this (just change docs/documentation.rst), or should I update it..?

**Comment by srepmub** [comment]
btw I thought python-six is not used anymore by shedskin.. ? and I assume pacboy automatically installes *-devel..? uhh and does 'clang' mean that gcc is not used anymore..? :P uhumuhmm

**Comment by carlkl** [comment]
I digging into it a little bit further. The usage of the progressbar is messy for windows, as you have to install blessings, blessed, and progressbar. blessings is a defined as dependancy but not needed for windows.

IMHO: it would be best to replace this stuff (blessings, blessed, progressbar and dependancies) alltogether with tqdm and colorama. This is the easiest solution I think.

I have some other recommendations for windows:

1. replace `-march=native` with `-march=core2` or `-march=nehalem` 
3.  use the `-D_WIN32`  macro rather `-DWIN32` as it is always defined (also with the `-std=c++17` flag given)
4. `-Wl,--enable-auto-import`  is default for binutils (mingw-w64) and is not needed in `FLAGS.mingw`
5. use `pcre2` instead of `pcre`?
7. some `WIN32` code paths are not needed any more. However this takes some time for testing and evaluation. 
8. testing shedskin with `clang++` and compare it to `g++` seems a good idea for me. For example: `clang++ -Wall` is much more informative than `g++ -Wall`. 
9. compare `shedskin` with `pythran` and `pyccel` (features, benchmark)

so many ideas, so little time ...

**Comment by srepmub** [comment]
I'm open to patches removing progressbar, blessings and jinja alltogether. it's on the list for 0.9.7 in any case.

the devel files should be necessary to compile shedskin-generated code further..? (with python-devel for shedskin -e).

**Comment by carlkl** [comment]
I didn't use the `-devel` packages until now. Seems to be unneccessary. I try to prepare a PR at the weekend for `tqdm` and maybe further enhancements. 

One issue more: `minilight` compiles but segfaults on windows.

**Comment by srepmub** [comment]
I'm wondering if we really need to depend on an external library to show a simple progressbar..? or to have colored output at all.. :P

**Comment by carlkl** [comment]
There is an even simpler variant: https://github.com/LoganGerber/better-progress  (MIT license)
But I havn't test it with windows up to now. (Terminal interaction is not that thrivial) 

The simplest solution would be to get rid of progress display at all....

**Comment by carlkl** [comment]
To get an idea how to display a progress with print statements

```python
import time
for i in range(0, 101, 10):
  print("\r>>> {}%".format(i), end='', flush=True)
  time.sleep(.3)
print("\r>>> 100% - Finished")
```

**Comment by srepmub** [comment]
another option is to make such imports optional, so use them if they are installed, otherwise do something basic.

**Comment by shakfu** [comment]
Note for this topic that the `blessings` and `progessbar2` dependencies are now gone and replaced by internal code in the `shedskin.utils` module.

**Comment by carlkl** [comment]
Tank you @shakfu and @srepmub

**Comment by srepmub** [comment]
wait, we didn't update the documentation yet.. :-)

**Comment by srepmub** [comment]
the jinja2 experiment, while interesting, has been reverted too (so pip should also not be necessary anymore?).

**Comment by shakfu** [comment]
@srepmub 

> the jinja2 experiment, while interesting, has been reverted too

I think that's right decision. I hesitated to remove it just in case it was required for `cmake` builds, but it's not since `cmake` has it's own builtin template/substitution engine. Agreed it's not a good fit right now for shedskin.

>  (so pip should also not be necessary anymore?).

`pip` is still a good idea to have to `pip install shedskin` option for new users, and also for the `dev` dependencies such as `[pytest, ..]`. 

In addition, I'm currently working on an option where shedskin will call [conan](https://conan.io) to download all of its dependencies (`gc`, `pcre`) and then use them in cmake seamlessly. The default is, of course, to look in the usual places `/usr/local/*` for the dependencies but this `conan` option means that shedskin can handle downloading dependencies into a local `.conan` cache, install them, and integrate automatically with cmake or another build method. 

In this case, if `conan` is not installed then `pip install conan` is required.

So I think the default option should be no dependencies and work as if everyone knows what they are doing (i.e. that they are capable to manually use their platform package manager to download dependencies or optionally have shedskin download a package manager (like conan) and have it download / integrate dependencies automatically.

**Comment by srepmub** [comment]
think we can continue under the 'cmake' issue

**Comment by shakfu** [comment]
Yup, windows issue can fall under cmake issue
