### ISSUE TITLE
Need a docker image

### ISSUE THREAD

**Issue by cyw3** [shedskin/shedskin#365]
Hi,

Can you provide a docker image with shedskin?

So that I don't need to build a enviroment for shedskin.

Thanks!

**Comment by srepmub** [comment]
hi,

we don't provide this, but if you are under windows perhaps WSL could be an easy solution to work with shedskin?

we are currently working on cmake-support so it should be much nicer to use shedskin under windows.

on other platforms, shedskin (master) has almost no dependencies, so should be easy to just install and use.

cheers.

**Comment by cyw3** [comment]
> hi,
> 
> we don't provide this, but if you are under windows perhaps WSL could be an easy solution to work with shedskin?
> 
> we are currently working on cmake-support so it should be much nicer to use shedskin under windows.
> 
> on other platforms, shedskin (master) has almost no dependencies, so should be easy to just install and use.
> 
> cheers.


I only have centos machine, and when i install `g++ libpcre++-dev python-all-dev libgc-dev`, i get lots of problems.

so a docker image with shedskin will be a goood choice for me.

**Comment by cyw3** [comment]
Ok, Thanks!
