### ISSUE TITLE
slowness introduced in c56a690588c419afc59de7c353d41ce77e72d47f

### ISSUE THREAD

**Issue by folkertvanheusden** [shedskin/shedskin#455]
I have a small test-program: a mandelbrot calculator in brainfuck that I compile to python using my toy compiler (https://vanheusden.com/compilers/brainfuck/).
As a test I compiled the result using shedskin v0.9.7 (dcc00cf565246f905dc1cbb733f5c6e35acee453) and shedskin v0.9.8 (44994c6cdd9ae660d96a5c05abcecba940e3e01f) to a native binary.
The run-time of v0.9.7 is 5.42 seconds.
The run-time of v0.9.8 is 8.32 seconds.
According to git bisect this is caused by c56a690588c419afc59de7c353d41ce77e72d47f.
If I use master *without* c56a690588c419afc59de7c353d41ce77e72d47f, then the run-time is back at 5.06 seconds(!).

**Comment by srepmub** [comment]
argh, it appears I was measuring this incorrectly somehow.. :S

commit reverted.

keeping the issue open to have another look at the 3x slowness caused by (unused!!) exception handling in __wrap.

**Comment by srepmub** [comment]
I was unable to get around the slowness, too bad.
