### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by micwoj92** [shedskin/shedskin#469]
Hello,

The license file states "the Shed Skin compiler (shedskin/*.py); License GNU GPL version 3".
However it does not say whether it is `GPL-3.0-only` or `GPL-3.0-or-later`, here are the SPDX identifiers: https://spdx.org/licenses/

It seems like different distributions interpret this differently.

Debian package states `GPL-3+` for this part:
https://metadata.ftp-master.debian.org/changelogs/main/s/shedskin/shedskin_0.9.4-1_copyright

Fedora mentions only `GPLv3`
https://src.fedoraproject.org/rpms/shedskin/blob/f31/f/shedskin.spec

**Comment by srepmub** [comment]
thanks for noting!

I think the Debian package is mistaken, as 'GPL version 3' does not imply any later versions.

adding 'or later' would mean trying to contact many contributors from way back, which might be a challenge.. so unless there is a good reason I think there is no need for this.

**Comment by micwoj92** [comment]
Also according to Wikipedia this project was started in 2005, which predates GPL3, but I think it is different question what was the license before.

**Comment by micwoj92** [comment]
I tried digging in deeper to find license pre gpl3 (2007), but could not find anything from prior first svn checkout (in 2008). From my side this is solved.
