### ISSUE TITLE
Variable names in produced Makefile should contain CXX, not CC for the C++ compiler.

### ISSUE THREAD

**Issue by yurivict** [shedskin/shedskin#471]
CC=g++ should become CXX?=g++.
CCFLAGS=... should become CXXFLAGS?=...

This would also allow to override these variables with environment variables and /etc/make.conf

**Comment by srepmub** [comment]
that sounds logical.. funny that this seems to have been like this for almost 20 years. would you be open to make a PR..?

**Comment by srepmub** [comment]
if not I'd be happy to make the change.

**Comment by yurivict** [comment]
https://github.com/shedskin/shedskin/pull/476

**Comment by srepmub** [comment]
merged, thanks again!
