### ISSUE TITLE
'self' converted to a string should contain the object pointer value

### ISSUE THREAD

**Issue by yurivict** [shedskin/shedskin#472]
Shed-skin prints this:
```
> print(f'self={self}')
self=<C instance>
```
while CPython prints this:
```
> print(f'{self}')
self=<c.C object at 0x2af7a6ef5b20>
```

Shed-skin should convert 'self' to string in a way similar to CPython because such string might be used as a key of some dictionary and such programs would fail in Shed-skin.

**Comment by srepmub** [comment]
ah, right! I never bothered with the address but it can make a difference indeed. I will push a fix for this shortly. note that you can also just use the objects as dict keys (so without converting them to a string) but you knew that..

**Comment by srepmub** [comment]
fix pushed.
