### ISSUE TITLE
Add python type annotations to shedskin code

### ISSUE THREAD

**Issue by shakfu** [shedskin/shedskin#479]
I've started to add type annotations in my [fork](https://github.com/shakfu/shedskin) so far I do believe it's proven to be useful and has the following immediate benefits:

- make the shedskin code more understandable in general, 
- track down type-related bugs, 
- provide in-code documentation, 
- indicate areas which can be improved

I'm using [mypy](https://github.com/python/mypy) via the command line as follows:

```bash
mypy --check-untyped-defs shedskin/cpp.py
```

.. after several commits , the remaining errors are attached in a text file.

[ss_type_errors.txt](https://github.com/user-attachments/files/15724996/ss_type_errors.txt)

**Comment by srepmub** [comment]
cool :-)

it is somewhat ironic that shedskin was started as an alternative to optimizers using type declarations (pyrex/cython) at the time. but since shedskin won't be able to bootstrap itself anyway.. :-)

feel free to push your commits, even if it only covers a certain part of the code or errors remain.

**Comment by shakfu** [comment]
Thanks @srepmub 

> feel free to push your commits, even if it only covers a certain part of the code or errors remain.

Ok, thanks. Before I do, I just to make explicit the process of annotating, in case someone else wants to help.

For a given module, annotate untyped function parameters via the following sequence:

1. Add obvious or self-evident type annotations if this is clear from context or usage and if the type is already available as a builtin or is already imported into the module's namespace. Do all of these first.

2. For remaining untyped parameters, if the parameter is consistently used across the project such as `gx` or `mv`, then import the relevant namespace using the following pattern to prevent cyclic dependencies and also eliminate the burden of type-specific imports:

```python
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from . import config
    from . import graph
```
The above idiom prevents imports under `TYPE_CHECKING` from occuring during runtime.


Annotations from these type-check specific imports would have to have be quoted like `gx: 'config.GlobalInfo'`

3. Check for runtime errors by running a basic test such as `shedskin build --spm hello.py`

```bash
shedskin build --spm hello.py
```

4. Check for type errors 

```bash
mypy --check-untyped-defs shedskin/cpp.py
```


The state of type annotation in python is covered very well by [PEP-649 Deferred Evaluation Of Annotations Using Descriptors](https://peps.python.org/pep-0649/).

**Comment by shakfu** [comment]
I'll merge the next round of fixes after tests pass... (attached is what seemingly remains)..

[ss_mypy_119.txt](https://github.com/user-attachments/files/15749817/ss_mypy_119.txt)

**Comment by srepmub** [comment]
hiya,

that also seems quite a bit of work!

do let me know if you run into anything really nasty, and maybe I can check
if that could lead to a code cleanup, bug fix or something.


cheers,
mark.

**Comment by shakfu** [comment]
@srepmub 

Can a `python.Class` have another `python.Class` as a parent? see python.py:457-8 which indicates that this is case..  If so I will add `self.parent: Optional['Class'] = None to `Class`

**Comment by srepmub** [comment]
good question. python.Class is only instantiated a few times.. if you look at graph.py you can see this is always added:

```
     newclass.module = self.module
     newclass.parent = python.StaticClass(newclass, getmv())
```

in a StaticClass instance, we maintain class-level attributes (vars), methods.. as opposed to instance-level stuff. for example, for a class 'Bert', we can have an attribute 'Bert.a' but also 'Bert().a'.. :)

**Comment by shakfu** [comment]
For the sake specifying what is possible: a python.Class can only have a python.Class or a python.StaticClass or both as a parent?

**Comment by srepmub** [comment]
only StaticClass. it's also not really optional, as every class definition gets a staticclass parent.

**Comment by srepmub** [comment]
I think this is done in the meantime? given that mypy --strict returned 0 errors recently..

**Comment by shakfu** [comment]
Yup... I will close it
