### ISSUE TITLE
44 tests fail

### ISSUE THREAD

**Issue by yurivict** [shedskin/shedskin#494]
See the [log](https://freebsd.org/~yuri/shed-skin-0.9.9-tests-failure.log).

Some tests fail to find test data.
Fir example the test ```test_satisfy``` fails to find the file ```../../testdata/uuf250-010.cnf```:

Test location: work-py311/shedskin-0.9.9/tests/test_prog_satisfy1/test_prog_satisfy1.py
Data location:
```
$ find . -name uuf250-010.cnf
./work-py311/shedskin-0.9.9/examples/testdata/uuf250-010.cnf
./work-py311/shedskin-0.9.9/tests/testdata/uuf250-010.cnf
```

Based on paths the file ```../../testdata/uuf250-010.cnf``` should be found, bit it isn't found for some reason.

**Comment by srepmub** [comment]
thanks for noting. are you running pytest in the shedskin root dir..? I never tried this, but it looks like it is picking up the test_*.py files, but not from the expected dir (shedskin/test). if you run pytest from shedskin/test, all the tests should run.. just using cpython that is. to run the tests using shedskin, you can use 'shedskin test' from shedskin/test or shedskin/examples.
