### ISSUE TITLE
python 3.13 support

### ISSUE THREAD

**Issue by srepmub** [shedskin/shedskin#499]
check if shedskin works with 3.13, and which new features we could add support for.

**Comment by srepmub** [comment]
loop over supported modules and check 'new in version..' comments. we have probably missed a few more things since 2.x.. :P

**Comment by shakfu** [comment]
I'm running 3.13 on macOS arm64, so far so good.

**Comment by srepmub** [comment]
do extension modules work?

**Comment by srepmub** [comment]
note, let's update CI to use 3.11-3.13 (if available)

**Comment by shakfu** [comment]
> do extension modules work?

I just tested a simple case and its compiles ok:

```python
# module demo.py
def test():
    print("OK")
```
but after testing it further, the `test` function is not available.

**Comment by shakfu** [comment]
Looks like there were [extensive changes](https://docs.python.org/3/whatsnew/3.13.html#c-api-changes) in 3.13

I will have a look

**Comment by srepmub** [comment]
for extension modules, you need to have an 'entry point' for the analysis, for example:

```
if __name__ == '__main__':
    test()
```

this is needed, as otherwise we don't know the types of the arguments to test.. though in this case there are no arguments.. which is something we could improve at some point perhaps ;-)

**Comment by srepmub** [comment]
testing with python 3.13 (conda) we get this warning:
```
/home/srepmub/shedskin/shedskin/makefile.py:66: SyntaxWarning: invalid escape sequence '\ '                                                 
  esc_space = "\ "    
```

**Comment by srepmub** [comment]
works with -fno-lto, but need to investigate further

**Comment by shakfu** [comment]
> for extension modules, you need to have an 'entry point' for the analysis, for example:
> ```
> 
> if __name__ == '__main__':
> 
>     test()
> 
> ```
> 
> this is needed, as otherwise we don't know the types of the arguments to test.. though in this case there are no arguments.. which is something we could improve at some point perhaps ;-)

Yes that worked. This should be probably be improved in this release as it'll likely surprise new users.

**Comment by srepmub** [comment]
not sure about that, since they do in many cases have to pass arguments.. 

shedskin also already warns about 'test' not being called, right?

we could just pick all functions without arguments, but that somehow doesn't sit right with me either.. since I like the 'not called' warnings shedskin gives you.

**Comment by srepmub** [comment]
okay probably conda's fault. when using python3.13 via a ubuntu PPA, I can build the DOOM extension module no problem.

will now try to upgrade CI.

**Comment by srepmub** [comment]
CI works without an issue with 3.13.

**Comment by srepmub** [comment]
the only thing left for this issue then, perhaps, is to check (again) for new features in 3.13 that we may want to deal with (either by supporting them or generating appropriate warnings/errors)

**Comment by shakfu** [comment]
> the only thing left for this issue then, perhaps, is to check (again) for new features in 3.13 that we may want to deal with (either by supporting them or generating appropriate warnings/errors)

Most of the key features in 3.13 are experimental like free threading support and the jit.

**Comment by srepmub** [comment]
from the 'whatsnew' page for 3.13, some changes that might be relevant:

-PythonFinalizationError -> new exception class, easy to add (just the definition) and use in os.fork[pty]
-base64.z85encode/z85decode methods -> if anyone is interested in adding this
-copy.replace -> let's ignore that
-str.replace(count-as-keyword) -> doesn't sound that hard?!
-array('u') -> array('w') -> unicode stuff, not so interesting.. perhaps we should raise an error here if not already
-itertools.batch(string arg) -> sounds easy.. but wait, we don't support batched. this was added in 3.12 apparently.
-re.error -> renamed to re.PatternError -> easy peasy

agreed if I make these into separate issues? do you see anything else for 3.13 (..3.12)? then with the separate issues we can close this one.

**Comment by srepmub** [comment]
closing this one. will create new issues for above. feel free to add more.
