### ISSUE TITLE
plot analysis time versus SLOC for example programs

### ISSUE THREAD

**Issue by srepmub** [shedskin/shedskin#513]
last time I plotted this (for my thesis) there were <20 examples..

**Comment by shakfu** [comment]
Ideally this should be done at a `shedskin test` with sloc and analysis time captured to an .sqlite db.

How does one get analysis time in shedskin?

**Comment by srepmub** [comment]
note that the sloc may require some logic. for extmods, we don't want to count *_main.py. and for example, for othello3, we don't want to count ref.py or gen.py.. for pycsg, we don't want to count core.py. I could make a full list of this.

**Comment by shakfu** [comment]
@srepmub I've added a `shedskin.stats` module which captures some values during analysis such as nwords of module, sloc, and analysis time in secs and stores it in a sqlite3 db in the shedskin cache directory if `--collect-stats` is passed. It's pretty rudimentary right now but the idea is use this to collect a lot more granular data.

It would be helpful if you also help with logic and also identifying some of the key datapoints to capture (and also where is the best point to capture)

**Comment by srepmub** [comment]
as mentioned in the PR, this is very nice! I will play a bit and make some changes.

**Comment by srepmub** [comment]
made some changes, so for the minilight example we count all imported (non-builtin) modules, also ignoring empty lines. this is pretty close to using the 'CLOC' utility I have been using, but it would be nice to get a bit closer..

I see quite a few recipes to try and accurately count SLOC for python files, so we could probably pick one of those (not sure which one yet). biggest difference with current shedskin.stats is probably to ignore (multi-line) docstrings.

thanks!!

**Comment by srepmub** [comment]
I will insert one of the recipes without too much consideration. feel free to replace with a better one!

**Comment by srepmub** [comment]
using the new stats module, I generated the following plot.

![harm](https://github.com/user-attachments/assets/c145596d-050e-42ea-920c-06e7a6c7a05d)

I did not add othello3.py, because that is so far out at 22K lines that it obscures the other points. I also left out 'amaze.py' which still encounters 'max iterations' for some reason, which can be classified as a bug.

**Comment by srepmub** [comment]
there is probably a closer correlation with the amount of "allocation sites" in each program, that shedskin has to disentangle. we could add some more metrics like this for 0.9.11.

**Comment by shakfu** [comment]
Do you mean memory allocation sites? I was thinking of capturing `graph.ModuleVisitor` stats... would that be useful?
