### ISSUE TITLE
eliminate CNode.fout

### ISSUE THREAD

**Issue by srepmub** [shedskin/shedskin#520]
this attribute is only used locally it seems, between infer.backflow_path and infer.flow_creation_sites. it's probably better for readability and for sure performance to just create a local dict in backflow_path and pass it to flow_creation_sites..

**Comment by shakfu** [comment]
@srepmub 

I'm not sure I understand your intent. From a quick read of both `backflow_path` and `flow_creation_sites`, and from the definition of `CNode.fout`, which are described as 

```python
class CNode:
    # ...
    self.fout: set[CNode] = set()  # unreal outgoing edges, used in ifa
```

I am assuming `.fout` is short for `.fan_out` or `.flow_out` to describe a directed edge from the `CNode` to another `CNode`.

I think it is reasonable to have this available as an attribute of the CNode.

If it is just a local variable created in `backflow_path` and passed on to `flow_creation_sites`, don't you lose the relevant data in the `CNode`?

**Comment by srepmub** [comment]
I think we could use a dictionary mapping nodes to fout, so something like `fout_dict[node] = set()` instead of 'node.fout = set()'..?

the attribute is only used locally, so we shouldn't lose any relevant data. and CNode will be cleaner (without a hard to describe attribute) and faster to copy/initialize.

**Comment by shakfu** [comment]
So create `fout_dict[node] = set()` in `backflow_path` which will now return a tuple of (list[CNode], dict[CNode, Set[CNode]]) with the later being passed on `flow_creation_sites` in `ifa_flow_graph`?

**Comment by srepmub** [comment]
well, since backflow_path is called multiple times, I would create a single dictionary (collections.defaultdict(set)?), which is updated several times by backflow_path.. then finally pass the dictionary to flow_creation_sites.

**Comment by shakfu** [comment]
@srepmub see [PR-522](https://github.com/shedskin/shedskin/pull/522)

**Comment by srepmub** [comment]
nice, thanks!!
